In [1]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

In [7]:
data1 = [6,7.5,8,0,1]

In [8]:
data1 *2

[6, 7.5, 8, 0, 1, 6, 7.5, 8, 0, 1]

In [9]:
arr1 = np.array(data1)
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [10]:
data2 = [[1,2,3,4], [5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
arr2.ndim

2

In [12]:
arr2.shape

(2, 4)

In [13]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [14]:
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [15]:
np.empty((2,3,2)) # 2*3*2 "null"값을 갖는 행렬

array([[[  5.87938119e-322,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000]],

       [[  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000]]])

In [16]:
np.array(range(15))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
np.array([2**x for x in range(1,101)]).reshape((10,10))


array([[2, 4, 8, 16, 32, 64, 128, 256, 512, 1024],
       [2048, 4096, 8192, 16384, 32768, 65536, 131072, 262144, 524288,
        1048576],
       [2097152, 4194304, 8388608, 16777216, 33554432, 67108864, 134217728,
        268435456, 536870912, 1073741824],
       [2147483648L, 4294967296L, 8589934592L, 17179869184L, 34359738368L,
        68719476736L, 137438953472L, 274877906944L, 549755813888L,
        1099511627776L],
       [2199023255552L, 4398046511104L, 8796093022208L, 17592186044416L,
        35184372088832L, 70368744177664L, 140737488355328L,
        281474976710656L, 562949953421312L, 1125899906842624L],
       [2251799813685248L, 4503599627370496L, 9007199254740992L,
        18014398509481984L, 36028797018963968L, 72057594037927936L,
        144115188075855872L, 288230376151711744L, 576460752303423488L,
        1152921504606846976L],
       [2305843009213693952L, 4611686018427387904L, 9223372036854775808L,
        18446744073709551616L, 36893488147419103232L,
        737869

In [27]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], 
      dtype='|S4')

In [28]:
names == 'Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

# 불리언 색인은 실제 데이터와 관련이 없다

In [38]:
data = np.random.randint(1,10, size=7)
data[names == 'Bob']

array([2, 1])

#  유니버설 함수

In [40]:
arr = np.arange(10)

In [41]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [42]:
arr = np.random.randn(4,4)
arr

array([[ 0.08573633, -1.56424369, -0.57867329, -0.76680559],
       [ 0.49866342,  1.20618166,  1.33296134, -0.3683067 ],
       [ 0.98222993, -1.43364017, -1.53725073,  0.44839044],
       [-0.22159229,  0.60614618, -0.42647604,  1.4321923 ]])

In [43]:
arr > 0

array([[ True, False, False, False],
       [ True,  True,  True, False],
       [ True, False, False,  True],
       [False,  True, False,  True]], dtype=bool)

In [44]:
np.where(arr>0, 2, -2)

array([[ 2, -2, -2, -2],
       [ 2,  2,  2, -2],
       [ 2, -2, -2,  2],
       [-2,  2, -2,  2]])

In [45]:
np.where(arr>0, 2, arr)

array([[ 2.        , -1.56424369, -0.57867329, -0.76680559],
       [ 2.        ,  2.        ,  2.        , -0.3683067 ],
       [ 2.        , -1.43364017, -1.53725073,  2.        ],
       [-0.22159229,  2.        , -0.42647604,  2.        ]])

In [46]:
np.where(cond1 & cond2, 0, np.where(cond1, 1, np.where(cond2, 2, 3)))

NameError: name 'cond1' is not defined

In [50]:
scores = np.random.randint(0, 100, (10, 3))
scores

array([[93, 78,  6],
       [31, 47, 64],
       [62, 87, 33],
       [15, 59, 90],
       [92, 10, 68],
       [23, 60, 73],
       [76, 78, 70],
       [17, 43, 67],
       [51, 48, 36],
       [52, 19,  6]])

In [51]:
np.where(scores < 60, 'F', np.where(scores < 70, 'D', np.where(scores < 80, 'C', np.where(scores < 90, 'B', 'A'))))

array([['A', 'C', 'F'],
       ['F', 'F', 'D'],
       ['D', 'B', 'F'],
       ['F', 'F', 'A'],
       ['A', 'F', 'D'],
       ['F', 'D', 'C'],
       ['C', 'C', 'C'],
       ['F', 'F', 'D'],
       ['F', 'F', 'F'],
       ['F', 'F', 'F']], 
      dtype='|S1')